-- Create a table for public profiles (synced with auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone
);

-- Turn on Row Level Security
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Create a table for user roles
create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  role text not null, -- e.g., 'admin', 'generator_user'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (user_id, role)
);

-- Turn on Row Level Security
alter table public.user_roles enable row level security;

-- Function to check admin status safely (bypass RLS)
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select exists (
    select 1 from public.user_roles 
    where user_id = auth.uid() 
    and role = 'admin'
  );
$$;

-- Create policies for user_roles
create policy "Users can read their own roles."
  on public.user_roles for select
  using ( auth.uid() = user_id );

create policy "Admins can read all roles."
  on public.user_roles for select
  using ( public.is_admin() );

create policy "Admins can insert roles."
  on public.user_roles for insert
  with check ( public.is_admin() );

create policy "Admins can delete roles."
  on public.user_roles for delete
  using ( public.is_admin() );


-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Helper to make the first user an admin (Replace 'YOUR_EMAIL' with actual email if needed, or run manually)
-- insert into public.user_roles (user_id, role)
-- select id, 'admin' from auth.users where email = 'your_email@example.com';
